# Generated by Django 3.1.5 on 2021-01-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Done', 'Done'), ('Close', 'Close')], max_length=200),
        ),
    ]
