# Generated by Django 3.1.5 on 2021-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210120_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='Quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
