# Generated by Django 3.1.5 on 2021-01-23 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_auto_20210120_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='Product',
            new_name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('No Response', 'No Response')], max_length=200),
        ),
    ]
